name: Fetch YouTube Data

on:
  schedule:
    - cron: "0 */12 * * *"   # alle 12 Stunden
  workflow_dispatch: {}       # manuell startbar

permissions:
  contents: write  # wichtig, damit der Bot Änderungen committen darf

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run fetch script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: node tools/youtube/fetch.js

      - name: Commit data updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json || true
          git diff --cached --quiet || git commit -m "chore(data): update YouTube cache"
          git push
